export default {
  fourthYear: [
    {
      name: "Mohneesh Kumar Swami",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/mohneesh-kumar-swami-87611b131/",
      imgName: "MohneeshSwami.jpeg",
    },
    {
      name: "Mukul Sharma",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/mukull/",
      imgName: "MukulSharma.jpeg",
    },
    {
      name: "Nilotpal Rai",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/nilotpalr/",
      imgName: "NilotpalRai.jpeg",
    },
    {
      name: "Abhishek Dadsena",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/abhishek-dadsena-87032720b/",
      imgName: "AbhishekDadsena.jpeg",
    },
    {
      name: "Hritik Gupta",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/hritik-gupta-96268b243/",
      imgName: "HritikGupta.jpeg",
    },
    {
      name: "Rupal Sharma",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/rupal-sharma-74441a215/",
      imgName: "RupalSharma.jpeg",
    },
    {
      name: "Avanish Mishra",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/avanish-mishra-b027a7205/",
      imgName: "AvanishMishra.jpeg",
    },
    {
      name: "Harsh Vardhan Kushwaha",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/harshvardhan-kushwaha-73371b201/",
      imgName: "HVKushwaha.jpeg",
    },
  ],

  thirdYear: [
    {
      name: "Aman Agarwal",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/aman-agarwal2003/",
      imgName: "AmanAgarwal.jpeg",
    },
    {
      name: "Vaibhav Kashyap",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/vaibhav-kashyap-7baa9a228/",
      imgName: "VaibhavKashyap.jpeg",
    },
    {
      name: "Utsav Chabhadiya",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/utsavchabhadiya/",
      imgName: "UtsavChabhadiya.jpeg",
    },
    {
      name: "Roushan Gupta",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/groushan/",
      imgName: "RoushanGupta.jpeg",
    },
    {
      name: "Jash Shah",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/jash-shah-3b4318224/",
      imgName: "JashShah.jpeg",
    },
    {
      name: "Vivek Pandey",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/vivek-pandey-159943223/",
      imgName: "VivekPandey.jpeg",
    },
    {
      name: "Raj Pandey",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/raj-pandey-b77ab2230/",
      imgName: "RajPandey.jpeg",
    },
    {
      name: "Pragya Bamrara",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/bamrarapragya/",
      imgName: "PragyaBamrara.jpeg",
    },
    {
      name: "Riddhiman Bannerjee",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/riddhiman-banerjee/",
      imgName: "RiddhimanBannerjee.jpeg",
    },
    {
      name: "Gaurav Bhardwaj",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/gaurav-bhardwaj-3b2ab721a/",
      imgName: "GauravBhardwaj.jpeg",
    },
    {
      name: "Vaishnavi Sharma",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/vaishnavi-sharma-08b32923a/",
      imgName: "VaishnaviSharma.jpeg",
    },
    {
      name: "Manish Rulaniya",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/manish-rulania/",
      imgName: "ManishRulaniya.jpeg",
    },
    {
      name: "Rudrapratap Singh Nimbla",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/nimbla/",
      imgName: "Rudy.jpeg",
    },
    {
      name: "Vaibhav Jain",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/vaibhavjain2004/",
      imgName: "VaibhavJain.jpeg",
    },
    {
      name: "Supesh Kumar Sinha",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/supesh/",
      imgName: "SupeshSinha.jpeg",
    },
    {
      name: "Sumit Raj",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/sumit1702/",
      imgName: "SumitRaj.jpeg",
    },
  ],

  secondYear: [
    {
      name: "Srushti Ratnaparkhi",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/srushti-ratnaparkhi-784479255/",
      imgName: "SrushtiRatnaparkhi.jpeg",
    },
    {
      name: "Hrushikesh Peddi",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/hrushikesh-peddi/",
      imgName: "Hrushikesh.jpeg",
    },
    {
      name: "Rohan Kumar",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/rohan-kumar-2ab212242/",
      imgName: "RohanKumar.jpeg",
    },
    {
      name: "Shretima Garg",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/shretimagarg/",
      imgName: "ShretimaGarg.jpeg",
    },
    {
      name: "Kchitiz Raj",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/kchitiz-raj-869681223/",
      imgName: "KchitizRaj.jpeg",
    },
    {
      name: "Vaishnavi Bandil",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/vaishnavi-bandil/",
      imgName: "VaishnaviBandil.jpeg",
    },
    {
      name: "Pranav Jha",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/pranav-jha-522789255/",
      imgName: "PranavJha.jpeg",
    },
    {
      name: "Karan Negi",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/karan-negi-744b54251/",
      imgName: "KaranNegi.jpeg",
    },
    {
      name: "Sarvagya Kaushik",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/sarvagya-kaushik-992496255/",
      imgName: "SarvagyaKaushik.jpeg",
    },
    {
      name: "Shambhavi Kumar",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/shambhavi-kumar-72435325a/",
      imgName: "ShambhaviKumar.jpeg",
    },
    {
      name: "Anjali Dahiya",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/anjali-dahiya/",
      imgName: "AnjaliDahiya.jpeg",
    },
    {
      name: "Pranjali Singh",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/pranjali-singh-8b4564214/",
      imgName: "PranjaliSingh.jpeg",
    },
    {
      name: "Mihir Kotaditya",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/mihir-kotadiya-177147267/",
      imgName: "MihirK.jpeg",
    },
    {
      name: "Sahebdeep Singh Kukreja",
      email: "harshitj.iitism@gmail.com",
      linkedin:
        "https://www.linkedin.com/in/sahebdeep-singh-kukreja-2b96a2212/",
      imgName: "Sahebdeep.jpeg",
    },
    {
      name: "Shivprasad Nirmale",
      email: "harshitj.iitism@gmail.com",
      linkedin: "https://www.linkedin.com/in/shivprasad-nirmale-562096255/",
      imgName: "Shivprasad.jpeg",
    },
    {
      name: "Yash Wardhan Singh Thakur",
      email: "yash.w.thakur@gmail.com",
      linkedin:
        "https://www.linkedin.com/in/yash-wardhan-singh-thakur-5678ab250/",
      imgName: "YashThakur.jpg",
    },
  ],
};
